<?php

return [
    'list' => [
        'Acacia Garden Center LLC',
        'Acacia LLC',
        'AL AWEER TRADING CO LTD',
        'APEX INFRA CONTRACTING',
        'ARTEVAL INTERIORS',
        'BIOSCAPE',
        'Landscape Elements LLC',
        'Metaline LLC',
        'Proscape FM LLC',
        'PROSCAPE GOLF',
        'PROSCAPE INFRA',
        'Proscape International Contracting',
        'Proscape LLC',
        'Stones & Slates LLC',
        'Tafani LLC',
        'Tanseeq Investment LLC',
        'Tanseeq LLC',
        'Tanseeq Projects LLC',
        'Tanseeq Realty LLC',
        'TANSEEQ TECHNOLOGIES',
        'Tanseeq Technologies FZCO',
        'Timbertech LLC',
        'Transmech LLC',
        'Unison Petra LLC',
        'URBAN DESIGN AND LANDSCAPE ARCHITECTURE FZ LLC',
        'Ventana LLC',
        'Water In Motion LLC',
        'Other',
    ],
];
